The casper module
The Casper class
Casper.options
clientScripts
exitOnError
httpStatusHandlers
logLevel
onAlert
onDie
onError
onLoadError
onPageInitialized
onResourceReceived
onResourceRequested
onStepComplete
onStepTimeout
onTimeout
onWaitTimeout
page
pageSettings
remoteScripts
safeLogs
silentErrors
stepTimeout
timeout
verbose
viewportSize
retryTimeout
waitTimeout
Casper prototype
back()
base64encode()
bypass()
click()
clickLabel()
capture()
captureBase64()
captureSelector()
clear()
debugHTML()
debugPage()
die()
download()
each()
eachThen()
echo()
evaluate()
evaluateOrDie()
exit()
exists()
fetchText()
forward()
log()
fill()
fillSelectors()
fillXPath()
getCurrentUrl()
getElementAttribute()
getElementsAttribute()
getElementBounds()
getElementsBounds()
getElementInfo()
getElementsInfo()
getFormValues()
getGlobal()
getHTML()
getPageContent()
getTitle()
mouseEvent()
open()
reload()
repeat()
resourceExists()
run()
scrollTo()
scrollToBottom()
sendKeys()
Options
setHttpAuth()
start()
status()
then()
thenBypass()
thenBypassIf()
thenBypassUnless()
thenClick()
thenEvaluate()
thenOpen()
thenOpenAndEvaluate()
toString()
unwait()
userAgent()
viewport()
visible()
wait()
waitFor()
waitForAlert()
waitForPopup()
waitForResource()
waitForUrl()
waitForSelector()
waitWhileSelector()
waitForSelectorTextChange()
waitForText()
waitUntilVisible()
waitWhileVisible()
warn()
withFrame()
withPopup()
zoom()
The clientutils module
Bookmarklet
ClientUtils prototype
echo()
encode()
exists()
findAll()
findOne()
getBase64()
getBinary()
getDocumentHeight()
getElementBounds()
getElementsBounds()
getElementByXPath()
getElementsByXPath()
getFieldValue()
getFormValues()
log()
mouseEvent()
removeElementsByXPath()
sendAJAX()
visible()
The colorizer module
Skipping CasperJS styling operations
Available predefined styles
colorize()
format()
///The mouse module
//The Mouse class
click()
doubleclick()
down()
move()
up()
///The tester module
//The Tester prototype
assert()
assert(Boolean condition[, String message])
assertDoesntExist()
assertDoesntExist(String selector[, String message])
assertEquals()
assertEquals(mixed testValue, mixed expected[, String message])
assertEval()
assertEval(Function fn[, String message, Mixed arguments])
assertEvalEquals()
assertEvalEquals(Function fn, mixed expected[, String message, Mixed arguments])
assertElementCount()
assertElementCount(String selector, Number count[, String message])
assertExists()
assertExists(String selector[, String message])
assertFalsy()
assertFalsy(Mixed subject[, String message])
assertField()
assertField(String|Object input, String expected[, String message, Object options])
assertFieldName()
assertFieldName(String inputName, String expected[, String message, Object options])
assertFieldCSS()
assertFieldCSS(String cssSelector, String expected, String message)
assertFieldXPath()
assertFieldXPath(String xpathSelector, String expected, String message)
assertHttpStatus()
assertHttpStatus(Number status[, String message])
assertMatch()
assertMatch(mixed subject, RegExp pattern[, String message])
assertNot()
assertNot(mixed subject[, String message])
assertNotEquals()
assertNotEquals(mixed testValue, mixed expected[, String message])
assertNotVisible()
assertNotVisible(String selector[, String message])
assertRaises()
assertRaises(Function fn, Array args[, String message])
assertSelectorDoesntHaveText()
assertSelectorDoesntHaveText(String selector, String text[, String message])
assertSelectorHasText()
assertSelectorHasText(String selector, String text[, String message])
assertResourceExists()
assertResourceExists(Function testFx[, String message])
assertTextExists()
assertTextExists(String expected[, String message])
assertTextDoesntExist()
assertTextDoesntExist(String unexpected[, String message])
assertTitle()
assertTitle(String expected[, String message])
assertTitleMatch()
assertTitleMatch(RegExp pattern[, String message])
assertTruthy()
assertTruthy(Mixed subject[, String message])
assertType()
assertType(mixed input, String type[, String message])
assertInstanceOf()
assertInstanceOf(mixed input, Function constructor[, String message])
assertUrlMatch()
assertUrlMatch(Regexp pattern[, String message])
assertVisible()
assertVisible(String selector[, String message])
begin()
begin(String description, Number planned, Function suite)
begin(String description, Function suite)
begin(String description, Number planned, Object config)
begin(String description, Object config)
colorize()
colorize(String message, String style)
comment()
comment(String message)
done()
error()
error(String message)
fail()
fail(String message)
formatMessage()
formatMessage(String message, String style)
getFailures()
getPasses()
info()
info(String message)
pass()
pass(String message)
renderResults()
renderResults(Boolean exit, Number status, String save)
setUp()
setUp([Function fn])
skip()
skip(Number nb, String message)
tearDown()
tearDown([Function fn])
///The utils module
//Functions reference
betterTypeOf()
betterInstanceOf()
dump()
fileExt()
fillBlanks()
format()
getPropertyPath()
inherits()
isArray()
isCasperObject()
isClipRect()
isFalsy()
isFunction()
isJsFile()
isNull()
isNumber()
isObject()
isString()
isTruthy()
isType()
isUndefined()
isWebPage()
mergeObjects()
node()
serialize()
unique()
